[tool.pytest.ini_options]
minversion = "7.3"
addopts = "-s -v --tb=long --cache-clear --flakes --cov=algorithmns --cov=data_structures"
testpaths = [
    "tests",
]
python_files = "tests.py test_*.py *_tests.py"